// Code generated by "stringer -type token"; DO NOT EDIT

package npmsemver

import "fmt"

const _token_name = "TokenIllegalTokenEOFTokenWsTokenNumberTokenIdentifierTokenPlaceholderTokenSeparatorTokenHyphenTokenBuildTokenPrereleaseTokenTildeTokenCaretTokenGTTokenLTTokenEqTokenNotTokenOrTokenAsterisk"

var _token_index = [...]uint8{0, 12, 20, 27, 38, 53, 69, 83, 94, 104, 119, 129, 139, 146, 153, 160, 168, 175, 188}

func (i token) String() string {
	if i < 0 || i >= token(len(_token_index)-1) {
		return fmt.Sprintf("token(%d)", i)
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
